name: Remove Bug Label
on:
  issues:
    types: [closed]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
    - name: Remove label
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let req = {
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          };
          const labelToRemove = 'bug';
          const issue = await github.rest.issues.get(req);
          console.log(issue);
          const labels = await github.rest.issues.getLabel(req);
          console.log(labels);
          const hasLabel = labels.data.some(label => label.name === labelToRemove);
          if (hasLabel) {
            await github.rest.issues.removeLabel({...req, name: labelToRemove});
          }
